### ISSUE TITLE
some questions with "UdemyEnrollEverywhere"

### ISSUE THREAD

**Issue by Imad-Sam** [keethesh/UdemyEnrollEverywhere#8]
hello guys
I installed "UdemyEnrollEverywhere".
but I have some questions :
1-How I use this program ? I opened the program but I don't know what must I do to enroll the course what I want?
2-Can this program enroll in any paid course what I want (with udemy url course for example)?
3-what is the "scrapers.py" file doing? I opened this program but I think it have a problem :
`
sys:1: RuntimeWarning: coroutine 'learnviral_wrapper' was never awaited
`
`
sys:1: RuntimeWarning: coroutine 'yofreesamples' was never awaited
`
no more questions and thanks for reading my questions I hope one can help me.

**Comment by keethesh** [comment]
1) All the instructions are in the README, please refer to it

2) No, what it does is that it scrapes 100% Udemy coupons from learnviral and yofreesamples, and attempts to add the course to your account

3) The script is currently not working, as Udemy has made some changes to their website. Will update it soon.

Don't hesitate if you have any other question🙂

**Comment by Imad-Sam** [comment]
thanks for answer my first questions.
I have some more questions :
1-
I read the file README , And I opened the file "main.py"
First the program wrote this :
`
[!] No cookies provided, trying to get them automatically...
`
`
[✓] Successfully extracted needed cookies from your browsers!
`
`
[!] Scraping courses from 2 websites...
`
`
[✓] Successfully scraped courses from YoFreeSamples in 3 seconds!
`
`
[✓] Successfully scraped courses from LearnViral in 8 seconds!
`
`
[✓] Scraped 1321 courses!
`
And when I press enter , the program write this :
`
Traceback (most recent call last):
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\helium\_impl\__init__.py", line 102, in _start_chrome_driver
    result = Chrome(options=chrome_options)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 136, in <module>
    browser = start_and_login()
  File "main.py", line 84, in start_and_login
    driver = helium.start_chrome("https://www.udemy.com/random_page_that_does_not_exist/",
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\helium\__init__.py", line 129, in start_chrome
    return _get_api_impl().start_chrome_impl(url, headless, options)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\helium\_impl\__init__.py", line 97, in start_chrome_impl
    chrome_driver = self._start_chrome_driver(headless, options)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\helium\_impl\__init__.py", line 106, in _start_chrome_driver
    result = Chrome(options=chrome_options, executable_path=driver_path)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Imad_Sammoud\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.19042 x86_64)
`
I don't know how I use the program even now.

2-
I wonder , can you write a program can make a coupons to any paid course we want for example : 

Udemy Course URL :  www.udemy.com/course/Course_Name/
How much discount do you want the coupon to deduct : 100% == For example
"Make Your Coupon" == Buttom
Your Coupon : ABCDEF == For example
---------------------------------------------------
If you write this program that will be wonderful.

**Comment by keethesh** [comment]
Unfortunately, generating coupons isn't possible. In fact, only the people who make courses and Udemy themselves can create coupons. If we could generate coupons whenever we want, it would have been a massive problem for Udemy!

**Comment by Imad-Sam** [comment]
Well I get that.
Well, can we write a program that takes a coupon made by the course owner that discounts 40%, for example, and makes it deduct 100%? If possible, not all course owners on Udemy create discount coupons for their courses.
I think this is possible, because I probably think that sites that offer 100% discount coupons for Udemy courses use coupons made by course owners and convert them into 100% discount coupons, right?

**Comment by keethesh** [comment]
Unfortunately once again, no :(
Course owners themselves decide to give free coupons, by generosity, or to make their course a little more popular! So not feasible.
And the fix for the script will be coming in some days. For real now. Like real real.

**Comment by Imad-Sam** [comment]
okay thank you friend you helped me so much.
